#!/usr/bin/env python3
"""Read the initial-error Monte Carlo back out. Generated by mc_1007.py.

  bash: for S in 0.1 0.3 1.0 3.0; do
            python3 mc_1007.py <line.h5> --seeds 30 --scale $S --out mc_1007_s$S.csv
        done
  then: python3 mc_table.py

THE RESULT, on the 1007.06 segment (Mag 5, sigma_beta = 100, lag 300 s, scored
from t = 0 so the transient counts), 30 seeds per row:

  scale      INS      EKF     caus     300s   c/EKF    win        p   s/EKF   win
    0.1     53.3     41.6     40.0     10.4   0.969  30/30   0.0000   0.250  30/30
    0.3    119.5     44.3     42.3     10.5   0.988  19/30   0.2005   0.241  30/30
    1.0    447.9     68.4     69.9     14.8   0.989  15/30   1.0000   0.203  30/30
    3.0   1344.2    208.9    201.2     42.8   0.877  27/30   0.0000   0.258  28/30

scale = 1 draws the initial navigation error from the prior the filter is
actually handed, whose 1 m/s per-axis velocity block leaves the INS a median
448 m out over ten minutes -- an order above this line's recorded 52 m. So the
realistic operating point is nearer scale 0.1, and the row that matters most is
the top one.

WHAT IT SAYS, in the order the claims should be made.

The smoothed output is not in doubt. Four to five times the EKF at every scale,
thirty seeds out of thirty at scale 1 and below. Nothing in this table
threatens it, and nothing in it is needed to support it.

The causal margin is roughly one percent and is NOT resolvable at a realistic
initial error. Rows 0.3 and 1.0 read 0.988 and 0.989 with 19 and 15 wins out of
30 -- a coin flip. That is the honest headline, and it agrees with the block
bootstrap, which found the EKF's own confidence interval swallowing our point
estimate whole.

Row 0.1's 30/30 must NOT be read as thirty independent confirmations. At a
tenth of the prior the perturbation barely moves the problem, so all thirty
runs are near-copies of the recorded line, which by itself reads 0.977 causal.
The seed-to-seed spread is 0.018 against a mean distance from parity of 0.031,
i.e. the scatter is 58% of the effect: the effective sample size is closer to
one than to thirty. What that row establishes is that the recorded line's small
causal margin is stable under perturbation, not that it is significant.

Row 3.0 is the one with real information. At three times the prior the margin
opens to 0.877 with 27 wins, and this is the fourth independent observation
that the graph's payoff scales with how badly conditioned the problem is: 1.06x
when well conditioned, 1.86x at sigma_beta = 1, 2.21x with the compensation
frozen, and now 1.14x at a cold start three times the assumed one. Relineari-
zation buys the basin, not the metres, and a badly started run is exactly when
the basin is in question. The tail is the price: the worst seed at scale 3 reads
3.24 causal and 3.20 smoothed, so a few starts leave the graph worse off than
the filter rather than better.

THE CONTROL, which is what actually decides the claim. Re-running the same
thirty seeds with --norelin freezes every linearization where a filter would
put it, leaving linear fixed-lag smoothing over the same model, lag and
measurements. Paired seed by seed, relin over norelin:

  scale       col    relin  norelin   ratio    win        p   worst
    0.1    causal     40.0     40.6   0.991  23/30   0.0052    1.01
    0.1  smoothed     10.4     10.6   0.966  26/30   0.0001    1.01
    3.0    causal    201.2    217.0   0.878  26/30   0.0001    2.90
    3.0  smoothed     42.8     62.1   0.713  17/30   0.5847    4.08

At a realistic initial error the formulation is worth one to three percent.
Consistent -- 23 and 26 seeds out of 30 -- but an effect that size is not a
contribution, and it says the graph is, for practical purposes, the linear
fixed-lag smoother that Section I already concedes is not new.

At three times the assumed initial error the causal row is the one real result
in this file: 12% with 26 of 30 seeds at p = 0.0001, and it is precisely what
turns the causal column from 0.999 against the EKF with 12 wins (norelin, a
dead tie) into 0.877 with 27 (relin, a win). The control isolates the
mechanism rather than merely correlating with it.

The smoothed row at that scale must NOT be read as a 29% gain. The geometric
mean of 0.713 sits on 17 wins out of 30 at p = 0.58: a few seeds gain hugely,
the median seed gains nothing, and the worst seed is 4.08x WORSE with
relinearization than without. Heavy tails in both directions, no reliable
effect.

CONSEQUENCE FOR THE MANUSCRIPT. The accuracy framing is dead: at the operating
point the manuscript reports, the graph and a linear smoother agree to within
3%. What survives is narrow and specific -- relinearization matters for the
CAUSAL output when the initial error is several times the assumed prior -- and
it comes with a tail, since the worst seed there runs 2.90x worse than the
frozen-linearization control on the same data.
"""
import csv
import math
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
SCALES = ("0.1", "0.3", "1.0", "3.0")


def sign_test(r):
    n = r.size
    w = int((r < 1).sum())
    k = min(w, n - w)
    return w, min(2 * sum(math.comb(n, i) for i in range(k + 1)) / 2 ** n, 1.0)


def main():
    print("initial-error MC, 1007.06 segment, whole segment scored (warm = 0)")
    print(f"{'scale':>6}{'INS':>9}{'EKF':>9}{'caus':>9}{'300s':>9}"
          f"{'c/EKF':>8}{'win':>7}{'p':>9}{'s/EKF':>8}{'win':>7}")
    rows = {}
    for s in SCALES:
        p = os.path.join(HERE, f"mc_1007_s{s}.csv")
        if not os.path.exists(p):
            continue
        r = list(csv.DictReader(open(p)))
        a = np.array([[float(x[k]) for k in
                       ("INS", "EKF", "FGO_causal", "FGO_smoothed")] for x in r])
        rc = a[:, 2] / a[:, 1]
        rs = a[:, 3] / a[:, 1]
        wc, pc = sign_test(rc)
        ws, _ = sign_test(rs)
        n = len(r)
        rows[s] = (a, rc, rs)
        print(f"{s:>6}{np.median(a[:,0]):9.1f}{np.median(a[:,1]):9.1f}"
              f"{np.median(a[:,2]):9.1f}{np.median(a[:,3]):9.1f}"
              f"{math.exp(np.log(rc).mean()):8.3f}{wc:>4}/{n}{pc:9.4f}"
              f"{math.exp(np.log(rs).mean()):8.3f}{ws:>4}/{n}")
    if not rows:
        print("  no mc_1007_s*.csv -- run mc_1007.py first")
        return
    print()
    print("effect against scatter -- how much each row's win count is worth")
    for s, (a, rc, rs) in rows.items():
        eff = abs(1 - rc.mean())
        print(f"  scale {s:>3}: INS {a[:,0].min():6.0f}-{a[:,0].max():6.0f} m   "
              f"c/EKF mean {rc.mean():.3f} sd {rc.std():.3f} "
              f"(scatter {100*rc.std()/max(eff,1e-9):3.0f}% of effect)   "
              f"worst c {rc.max():.2f}  worst s {rs.max():.2f}")


if __name__ == "__main__":
    main()
